# ==============================
# Site settings
# ==============================
title: "Zetao Fei-test"
tagline: "Postdoctoral Fellow at École Polytechnique"
email: "zetao.fei@polytechnique.edu"
author: "Zetao Fei"
description: "Research interests: inverse problems, imaging, wave physics"
baseurl: "" # the subpath of your site, e.g. /academicpages
url: "https://fei-zetao.github.io" # your GitHub Pages URL


# ==============================
# Theme settings
# ==============================
theme: academicpages
header_pages:
  - index.md
  - research.md
  - publications.md
  - teaching.md
  - contact.md

# ==============================
# Footer and social links
# ==============================
footer: "© 2025 Zetao Fei"
show_sitemap: true
show_rss: true
show_related_posts: true
show_share_buttons: true

# ==============================
# Build settings
# ==============================
markdown: kramdown
highlighter: rouge

# ==============================
# Navigation
# ==============================
navigation:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
  - title: "Publications"
    url: /publications/
  - title: "Teaching"
    url: /teaching/
  - title: "Contact"
    url: /contact/

